/**
 * Keeps the database mirror of the reference data in step with content/ (ADR-028).
 *
 *   npm run db:reference
 *       Regenerates supabase/tests/database/reference_data.test.sql, the pgTAP test that
 *       proves the migrations produce exactly content/.
 *   npm run db:reference -- --new-migration <name>
 *       Also writes supabase/migrations/<UTC timestamp>_<name>.sql with the idempotent sync
 *       statements for the current content. Use it whenever reference content changes:
 *       migrations already applied to a hosted project are never edited (ADR-017).
 */
import { writeFile } from "node:fs/promises";
import path from "node:path";
import { getReferenceData } from "../lib/content/reference-data";
import { referenceSyncSql, referenceTestSql } from "../lib/supabase/reference-sql";

const ROOT = path.resolve(import.meta.dirname, "..");
export const REFERENCE_TEST_PATH = "supabase/tests/database/reference_data.test.sql";

function migrationTimestamp(now: Date): string {
  return now.toISOString().replace(/[-:T]/g, "").slice(0, 14);
}

async function main() {
  const data = getReferenceData();
  await writeFile(path.join(ROOT, REFERENCE_TEST_PATH), referenceTestSql(data));
  console.log(`Wrote ${REFERENCE_TEST_PATH}`);

  const flag = process.argv.indexOf("--new-migration");
  if (flag === -1) return;
  const name = process.argv[flag + 1];
  if (name === undefined || !/^[a-z0-9_]+$/.test(name)) {
    console.error("Usage: npm run db:reference -- --new-migration <snake_case_name>");
    process.exit(1);
  }
  const file = `supabase/migrations/${migrationTimestamp(new Date())}_${name}.sql`;
  const header = [
    "-- GENERATED by `npm run db:reference -- --new-migration` from content/ (ADR-028).",
    "-- Reference data (not demo data): school years, periods, public holidays, calendar",
    "-- exceptions, education levels and curricula. Idempotent. Never edit once applied to a",
    "-- hosted project: change content/ and generate a new migration instead.",
    "",
    "",
  ].join("\n");
  await writeFile(path.join(ROOT, file), header + referenceSyncSql(data));
  console.log(`Wrote ${file}`);
}

await main();
