/** Generates the bounded authoring/media inventory; never changes lessons or approvals. */
import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { generateSchoolDays } from "../domain/calendar/school-days";
import { generateDailyPlan } from "../domain/programme/daily-plan";
import { getProgramme, getReferenceData } from "../lib/content/reference-data";
import { REVIEW_PACKAGES, reviewPackagePath } from "../lib/content/review-packages";
import { buildReviewPackage } from "../lib/content/review-package";
import { picturesOf } from "../lib/content/visual-audit";

const data = getReferenceData();
const programme = getProgramme("maternelle-3", "2026-2027", data)!;
const plans = generateSchoolDays(
  data.calendars.find((c) => c.schoolYear.id === "2026-2027")!,
  data.publicHolidays,
)
  .filter(
    (d) => d.instructionalDay !== null && d.instructionalDay >= 30 && d.instructionalDay <= 44,
  )
  .map((d) => generateDailyPlan(d, programme, data.lessons));
assert.equal(plans.length, 15);
const lessons = plans.flatMap((p) => p.sessions.map((s) => s.lesson!));
assert.equal(lessons.length, 60);
for (const p of plans) {
  assert.equal(p.status, "complete");
  assert.equal(p.totalMinutes, 35);
}
for (const l of lessons) {
  assert.equal(l.status, "review");
  assert.equal(l.review, null);
}
const lines = [
  "# October Weeks 3–5 source and media inventory",
  "",
  "Generated by `node --import tsx scripts/october-weeks-3-5-evidence.ts` from canonical content. This is not an independent verdict.",
  "",
  "## Day and lesson mapping",
  "",
  "| Day | Date | Rotating domain | Exact lesson IDs | Minutes |",
  "| --- | --- | --- | --- | --- |",
  ...plans.map(
    (p) =>
      `| ${p.instructionalDay} | ${p.date} | ${p.sessions[3]!.domainCode} | ${p.sessions.map((s) => `\`${s.lesson!.id}\``).join(", ")} | ${p.totalMinutes} |`,
  ),
  "",
  "## Package freshness",
  "",
  "Canonical selection: curriculum `maternelle-cycle1-cd-2026`, level `maternelle-3`, school year `2026-2027`. Source: the six level lesson JSON files, programme/annual plan, objectives, calendars, media registry, materials, teaching texts and review history loaded by `lib/content/reference-data.ts`.",
  "",
  "All registered packages are compared as complete UTF-8 strings against in-memory canonical regeneration; any difference aborts generation.",
  "",
  "| Package | Days | Equality | SHA-256 |",
  "| --- | --- | --- | --- |",
];
for (const options of REVIEW_PACKAGES) {
  const file = reviewPackagePath(options);
  const saved = readFileSync(file, "utf8");
  assert.equal(saved, buildReviewPackage(data, options), file);
  if (options.levelId === "maternelle-3" && options.fromDay >= 30)
    lines.push(
      `| [Week ${options.week}](${file.split("/").at(-1)}) | ${options.fromDay}-${options.toDay} | exact | \`${createHash("sha256").update(saved).digest("hex")}\` |`,
    );
}
lines.push(
  "",
  `All ${REVIEW_PACKAGES.length} registered packages are fresh. The three weekly packages form one independent-review batch, not three separate approval gates.`,
  "",
  "## Every new activity: media classification",
  "",
  "Real objects, adult-drawn paper numerals/motifs and spoken month names are physical/oral teaching supports, not missing screen media. Existing linked text illustrations are reused without changing their accepted bytes or associations. The plant drawing recalls Batch 1; it does not claim to display a new stage diagram.",
  "",
  "| Day | Activity | Classification | Existing media/text IDs or physical support |",
  "| --- | --- | --- | --- |",
);
const counts = { "no media required": 0, "reuse accepted asset": 0 };
for (const p of plans) {
  for (const s of p.sessions) {
    for (const a of s.lesson!.activities) {
      const textId = typeof a.payload["textId"] === "string" ? a.payload["textId"] : null;
      const ids = picturesOf(a, data);
      const classification = ids.length ? "reuse accepted asset" : "no media required";
      counts[classification]++;
      const support =
        [textId ? `text: ${textId}` : "", ...ids, ...a.materialCodes.filter((c) => c !== "aucun")]
          .filter(Boolean)
          .join(", ") || "oral parent-child interaction";
      lines.push(`| ${p.instructionalDay} | \`${a.id}\` | ${classification} | ${support} |`);
    }
  }
}
lines.push(
  "",
  `${Object.values(counts).reduce((a, b) => a + b, 0)} activities: ${counts["no media required"]} no media required, ${counts["reuse accepted asset"]} reuse accepted assets; zero new deterministic SVGs, zero required rich or multi-frame ImageGen candidates.`,
  "",
  "Future optional rich variants (child life stages and biodiversity care) are specified in `docs/work/OCTOBER_WEEKS_3_5.md`. They are not current dependencies, placeholders or generation authorizations. Do not substitute weak diagrams for a later expressive/narrative illustration request.",
  "",
);
writeFileSync("docs/review/OCTOBER_WEEKS_3_5_MEDIA.md", lines.join("\n"));
console.log(
  `Generated media/source inventory for ${lessons.length} lessons and ${Object.values(counts).reduce((a, b) => a + b, 0)} activities; ${REVIEW_PACKAGES.length} packages fresh.`,
);
