-- GENERATED by `npm run db:reference -- --new-migration` from content/ (ADR-028).
-- Reference data (not demo data): school years, periods, public holidays, calendar
-- exceptions, education levels and curricula. Idempotent. Never edit once applied to a
-- hosted project: change content/ and generate a new migration instead.

-- 1. Remove reference rows that are no longer in content/ (children first). A row still
--    referenced by other data makes this fail: nothing is deleted silently.

delete from public.school_year_curricula
where (school_year_id, stage_id) not in (
  values
    ('2026-2027'::text, 'maternelle'::text)
);

delete from public.curriculum_domains
where (curriculum_id, code) not in (
  values
    ('maternelle-cycle1-cd-2026'::text, 'ART'::text),
    ('maternelle-cycle1-cd-2026'::text, 'LANG'::text),
    ('maternelle-cycle1-cd-2026'::text, 'MATH'::text),
    ('maternelle-cycle1-cd-2026'::text, 'PHYS'::text),
    ('maternelle-cycle1-cd-2026'::text, 'TIME-SPACE'::text),
    ('maternelle-cycle1-cd-2026'::text, 'WORLD'::text)
);

delete from public.curriculum_levels
where (curriculum_id, level_id) not in (
  values
    ('maternelle-cycle1-cd-2026'::text, 'maternelle-1'::text),
    ('maternelle-cycle1-cd-2026'::text, 'maternelle-2'::text),
    ('maternelle-cycle1-cd-2026'::text, 'maternelle-3'::text)
);

delete from public.curricula
where (id) not in (
  values
    ('maternelle-cycle1-cd-2026'::text)
);

delete from public.calendar_exceptions
where (id) not in (
  values
    ('2026-2027-detente-trimestre-1'::text),
    ('2026-2027-detente-trimestre-2'::text),
    ('2026-2027-vacances-trimestre-1'::text),
    ('2026-2027-vacances-trimestre-2'::text)
);

delete from public.public_holidays
where (id) not in (
  values
    ('combat-simon-kimbangu'::text),
    ('fete-des-parents'::text),
    ('fete-du-travail'::text),
    ('forces-armees'::text),
    ('heros-national-kabila'::text),
    ('heros-national-lumumba'::text),
    ('independance'::text),
    ('martyrs-independance'::text),
    ('noel'::text),
    ('nouvel-an'::text)
);

delete from public.school_periods
where (school_year_id, position) not in (
  values
    ('2026-2027'::text, 1::smallint),
    ('2026-2027'::text, 2::smallint),
    ('2026-2027'::text, 3::smallint),
    ('2026-2027'::text, 4::smallint),
    ('2026-2027'::text, 5::smallint),
    ('2026-2027'::text, 6::smallint)
);

delete from public.school_years
where (id) not in (
  values
    ('2026-2027'::text)
);

delete from public.school_levels
where (id) not in (
  values
    ('maternelle-1'::text),
    ('maternelle-2'::text),
    ('maternelle-3'::text)
);

delete from public.education_stages
where (id) not in (
  values
    ('maternelle'::text)
);

-- 2. Insert or update every reference row (parents first). Unchanged rows are untouched.

insert into public.education_stages (id, position, name)
values
  ('maternelle'::text, 1::smallint, 'Enseignement maternel'::text)
on conflict (id) do update set
  position = excluded.position,
  name = excluded.name
where (education_stages.position, education_stages.name)
  is distinct from (excluded.position, excluded.name);

insert into public.school_levels (id, stage_id, position, name)
values
  ('maternelle-1'::text, 'maternelle'::text, 1::smallint, '1ère maternelle'::text),
  ('maternelle-2'::text, 'maternelle'::text, 2::smallint, '2ème maternelle'::text),
  ('maternelle-3'::text, 'maternelle'::text, 3::smallint, '3ème maternelle'::text)
on conflict (id) do update set
  stage_id = excluded.stage_id,
  position = excluded.position,
  name = excluded.name
where (school_levels.stage_id, school_levels.position, school_levels.name)
  is distinct from (excluded.stage_id, excluded.position, excluded.name);

insert into public.school_years (id, label, starts_on, ends_on, instructional_weekdays, authority, verification, source, notes)
values
  ('2026-2027'::text, '2026–2027'::text, '2026-09-01'::date, '2027-07-02'::date, '{1,2,3,4,5}'::smallint[], 'ministry'::text, 'verified'::text, 'Calendrier scolaire 2026-2027, Ministère de l’Éducation nationale et Nouvelle Citoyenneté (MINEDU-NC), Kinshasa, 26 juin 2026, § IV.1 Enseignement maternel — https://edu-nc.gouv.cd/docs/1784193331_CALENDRIER%20SCOLAIRE%202026%20%E2%80%93%202027%20F_copy.pdf'::text, 'Maternelle: children''s activities run Monday to Friday. The calendar also counts four Saturdays as working days (14 Nov 2026, 27 Feb, 20 Mar and 29 May 2027) for results and report cards; they are not children''s activity days, so they are not instructional days in Teka Edu. The ministry announces 192 working days including those Saturdays.'::text)
on conflict (id) do update set
  label = excluded.label,
  starts_on = excluded.starts_on,
  ends_on = excluded.ends_on,
  instructional_weekdays = excluded.instructional_weekdays,
  authority = excluded.authority,
  verification = excluded.verification,
  source = excluded.source,
  notes = excluded.notes
where (school_years.label, school_years.starts_on, school_years.ends_on, school_years.instructional_weekdays, school_years.authority, school_years.verification, school_years.source, school_years.notes)
  is distinct from (excluded.label, excluded.starts_on, excluded.ends_on, excluded.instructional_weekdays, excluded.authority, excluded.verification, excluded.source, excluded.notes);

insert into public.school_periods (school_year_id, position, term, starts_on, ends_on)
values
  ('2026-2027'::text, 1::smallint, 1::smallint, '2026-09-01'::date, '2026-11-04'::date),
  ('2026-2027'::text, 2::smallint, 1::smallint, '2026-11-09'::date, '2026-12-22'::date),
  ('2026-2027'::text, 3::smallint, 2::smallint, '2027-01-11'::date, '2027-02-17'::date),
  ('2026-2027'::text, 4::smallint, 2::smallint, '2027-02-22'::date, '2027-03-20'::date),
  ('2026-2027'::text, 5::smallint, 3::smallint, '2027-04-05'::date, '2027-05-21'::date),
  ('2026-2027'::text, 6::smallint, 3::smallint, '2027-05-24'::date, '2027-07-02'::date)
on conflict (school_year_id, position) do update set
  term = excluded.term,
  starts_on = excluded.starts_on,
  ends_on = excluded.ends_on
where (school_periods.term, school_periods.starts_on, school_periods.ends_on)
  is distinct from (excluded.term, excluded.starts_on, excluded.ends_on);

insert into public.public_holidays (id, name, month, day, valid_from, valid_until, authority, verification, source, notes)
values
  ('combat-simon-kimbangu'::text, 'Journée du combat de Simon Kimbangu et de la conscience africaine'::text, 4::smallint, 6::smallint, null::date, null::date, 'law'::text, 'verified'::text, 'Ordonnance n° 23/042 du 30 mars 2023 fixant la liste des jours fériés légaux en République démocratique du Congo, art. 1'::text, 'Added to the legal list by Ordonnance n° 23/042 (2023).'::text),
  ('fete-des-parents'::text, 'Fête des parents'::text, 8::smallint, 1::smallint, null::date, null::date, 'law'::text, 'verified'::text, 'Ordonnance n° 23/042 du 30 mars 2023 fixant la liste des jours fériés légaux en République démocratique du Congo, art. 1'::text, null::text),
  ('fete-du-travail'::text, 'Fête du travail'::text, 5::smallint, 1::smallint, null::date, null::date, 'law'::text, 'verified'::text, 'Ordonnance n° 23/042 du 30 mars 2023 fixant la liste des jours fériés légaux en République démocratique du Congo, art. 1'::text, null::text),
  ('forces-armees'::text, 'Journée des Forces armées'::text, 5::smallint, 17::smallint, null::date, null::date, 'law'::text, 'verified'::text, 'Ordonnance n° 23/042 du 30 mars 2023 fixant la liste des jours fériés légaux en République démocratique du Congo, art. 1'::text, 'Also called « Journée de la Révolution et des Forces armées » or « Journée des FARDC » in official communications; the name here is the ordinance''s.'::text),
  ('heros-national-kabila'::text, 'Journée du héros national Laurent Désiré Kabila'::text, 1::smallint, 16::smallint, null::date, null::date, 'law'::text, 'verified'::text, 'Ordonnance n° 23/042 du 30 mars 2023 fixant la liste des jours fériés légaux en République démocratique du Congo, art. 1'::text, null::text),
  ('heros-national-lumumba'::text, 'Journée du héros national Patrice Emery Lumumba'::text, 1::smallint, 17::smallint, null::date, null::date, 'law'::text, 'verified'::text, 'Ordonnance n° 23/042 du 30 mars 2023 fixant la liste des jours fériés légaux en République démocratique du Congo, art. 1'::text, null::text),
  ('independance'::text, 'Journée de l’indépendance'::text, 6::smallint, 30::smallint, null::date, null::date, 'law'::text, 'verified'::text, 'Ordonnance n° 23/042 du 30 mars 2023 fixant la liste des jours fériés légaux en République démocratique du Congo, art. 1'::text, null::text),
  ('martyrs-independance'::text, 'Journée des Martyrs de l’indépendance'::text, 1::smallint, 4::smallint, null::date, null::date, 'law'::text, 'verified'::text, 'Ordonnance n° 23/042 du 30 mars 2023 fixant la liste des jours fériés légaux en République démocratique du Congo, art. 1'::text, null::text),
  ('noel'::text, 'Noël'::text, 12::smallint, 25::smallint, null::date, null::date, 'law'::text, 'verified'::text, 'Ordonnance n° 23/042 du 30 mars 2023 fixant la liste des jours fériés légaux en République démocratique du Congo, art. 1'::text, null::text),
  ('nouvel-an'::text, 'Nouvel an'::text, 1::smallint, 1::smallint, null::date, null::date, 'law'::text, 'verified'::text, 'Ordonnance n° 23/042 du 30 mars 2023 fixant la liste des jours fériés légaux en République démocratique du Congo, art. 1'::text, null::text)
on conflict (id) do update set
  name = excluded.name,
  month = excluded.month,
  day = excluded.day,
  valid_from = excluded.valid_from,
  valid_until = excluded.valid_until,
  authority = excluded.authority,
  verification = excluded.verification,
  source = excluded.source,
  notes = excluded.notes
where (public_holidays.name, public_holidays.month, public_holidays.day, public_holidays.valid_from, public_holidays.valid_until, public_holidays.authority, public_holidays.verification, public_holidays.source, public_holidays.notes)
  is distinct from (excluded.name, excluded.month, excluded.day, excluded.valid_from, excluded.valid_until, excluded.authority, excluded.verification, excluded.source, excluded.notes);

insert into public.calendar_exceptions (id, school_year_id, kind, starts_on, ends_on, name, public_holiday_id, authority, verification, source, notes)
values
  ('2026-2027-detente-trimestre-1'::text, '2026-2027'::text, 'school-vacation'::text, '2026-11-05'::date, '2026-11-07'::date, 'Congé de détente du 1er trimestre'::text, null::text, 'ministry'::text, 'verified'::text, 'Calendrier scolaire 2026-2027 (MINEDU-NC, 26 juin 2026), § IV.1'::text, null::text),
  ('2026-2027-detente-trimestre-2'::text, '2026-2027'::text, 'school-vacation'::text, '2027-02-18'::date, '2027-02-20'::date, 'Congé de détente du 2ème trimestre'::text, null::text, 'ministry'::text, 'verified'::text, 'Calendrier scolaire 2026-2027 (MINEDU-NC, 26 juin 2026), § IV.1'::text, null::text),
  ('2026-2027-vacances-trimestre-1'::text, '2026-2027'::text, 'school-vacation'::text, '2026-12-23'::date, '2027-01-09'::date, 'Vacances du 1er trimestre'::text, null::text, 'ministry'::text, 'verified'::text, 'Calendrier scolaire 2026-2027 (MINEDU-NC, 26 juin 2026), § IV.1'::text, null::text),
  ('2026-2027-vacances-trimestre-2'::text, '2026-2027'::text, 'school-vacation'::text, '2027-03-22'::date, '2027-04-03'::date, 'Vacances du 2ème trimestre'::text, null::text, 'ministry'::text, 'verified'::text, 'Calendrier scolaire 2026-2027 (MINEDU-NC, 26 juin 2026), § IV.1'::text, null::text)
on conflict (id) do update set
  school_year_id = excluded.school_year_id,
  kind = excluded.kind,
  starts_on = excluded.starts_on,
  ends_on = excluded.ends_on,
  name = excluded.name,
  public_holiday_id = excluded.public_holiday_id,
  authority = excluded.authority,
  verification = excluded.verification,
  source = excluded.source,
  notes = excluded.notes
where (calendar_exceptions.school_year_id, calendar_exceptions.kind, calendar_exceptions.starts_on, calendar_exceptions.ends_on, calendar_exceptions.name, calendar_exceptions.public_holiday_id, calendar_exceptions.authority, calendar_exceptions.verification, calendar_exceptions.source, calendar_exceptions.notes)
  is distinct from (excluded.school_year_id, excluded.kind, excluded.starts_on, excluded.ends_on, excluded.name, excluded.public_holiday_id, excluded.authority, excluded.verification, excluded.source, excluded.notes);

insert into public.curricula (id, stage_id, name, version, status, reference_title, reference_publisher, reference_citation, reference_url, reference_verification, adaptation_note)
values
  ('maternelle-cycle1-cd-2026'::text, 'maternelle'::text, 'Teka Edu Maternelle — Cycle 1 adapté pour la RDC'::text, '2026'::text, 'active'::text, 'Programme d’enseignement de l’école maternelle (cycle 1)'::text, 'Ministère de l’Éducation nationale (France)'::text, 'Arrêté du 16 avril 2026 fixant le programme d’enseignement de l’école maternelle (cycle 1), NOR MENE2608627A, BO n° 19 du 7 mai 2026, applicable from the 2026-2027 school year. Domains 1 and 4: annexes 1 and 2 of the arrêté du 22 octobre 2024, NOR MENE2415135A, BO n° 41 du 31 octobre 2024.'::text, 'https://www.education.gouv.fr/bo/2026/Hebdo19/MENE2608627A'::text, 'verified'::text, 'Teka Edu adaptation for the DRC (Teka Edu decision, not an official DRC programme): DRC school calendar and holidays, Congolese or universal examples, French-first with optional English scaffolding. The 2026 French programme states objectives by age band (before 4, from 4, from 5); Teka Edu maps its classes to the French sections PS, MS and GS.'::text)
on conflict (id) do update set
  stage_id = excluded.stage_id,
  name = excluded.name,
  version = excluded.version,
  status = excluded.status,
  reference_title = excluded.reference_title,
  reference_publisher = excluded.reference_publisher,
  reference_citation = excluded.reference_citation,
  reference_url = excluded.reference_url,
  reference_verification = excluded.reference_verification,
  adaptation_note = excluded.adaptation_note
where (curricula.stage_id, curricula.name, curricula.version, curricula.status, curricula.reference_title, curricula.reference_publisher, curricula.reference_citation, curricula.reference_url, curricula.reference_verification, curricula.adaptation_note)
  is distinct from (excluded.stage_id, excluded.name, excluded.version, excluded.status, excluded.reference_title, excluded.reference_publisher, excluded.reference_citation, excluded.reference_url, excluded.reference_verification, excluded.adaptation_note);

insert into public.curriculum_levels (curriculum_id, level_id, stage_id, reference_section)
values
  ('maternelle-cycle1-cd-2026'::text, 'maternelle-1'::text, 'maternelle'::text, 'PS'::text),
  ('maternelle-cycle1-cd-2026'::text, 'maternelle-2'::text, 'maternelle'::text, 'MS'::text),
  ('maternelle-cycle1-cd-2026'::text, 'maternelle-3'::text, 'maternelle'::text, 'GS'::text)
on conflict (curriculum_id, level_id) do update set
  stage_id = excluded.stage_id,
  reference_section = excluded.reference_section
where (curriculum_levels.stage_id, curriculum_levels.reference_section)
  is distinct from (excluded.stage_id, excluded.reference_section);

insert into public.curriculum_domains (curriculum_id, code, kind, position, title, is_active)
values
  ('maternelle-cycle1-cd-2026'::text, 'ART'::text, 'learning-domain'::text, 3::smallint, 'Agir, s’exprimer, comprendre à travers les activités artistiques'::text, true),
  ('maternelle-cycle1-cd-2026'::text, 'LANG'::text, 'learning-domain'::text, 1::smallint, 'Le développement et la structuration du langage oral et écrit'::text, true),
  ('maternelle-cycle1-cd-2026'::text, 'MATH'::text, 'learning-domain'::text, 4::smallint, 'L’acquisition des premiers outils mathématiques'::text, true),
  ('maternelle-cycle1-cd-2026'::text, 'PHYS'::text, 'learning-domain'::text, 2::smallint, 'Agir, s’exprimer, comprendre à travers les activités physiques'::text, true),
  ('maternelle-cycle1-cd-2026'::text, 'TIME-SPACE'::text, 'learning-domain'::text, 5::smallint, 'Se repérer dans le temps et l’espace'::text, true),
  ('maternelle-cycle1-cd-2026'::text, 'WORLD'::text, 'learning-domain'::text, 6::smallint, 'Découvrir le monde du vivant, de la matière et des objets'::text, true)
on conflict (curriculum_id, code) do update set
  kind = excluded.kind,
  position = excluded.position,
  title = excluded.title,
  is_active = excluded.is_active
where (curriculum_domains.kind, curriculum_domains.position, curriculum_domains.title, curriculum_domains.is_active)
  is distinct from (excluded.kind, excluded.position, excluded.title, excluded.is_active);

insert into public.school_year_curricula (school_year_id, stage_id, curriculum_id)
values
  ('2026-2027'::text, 'maternelle'::text, 'maternelle-cycle1-cd-2026'::text)
on conflict (school_year_id, stage_id) do update set
  curriculum_id = excluded.curriculum_id
where (school_year_curricula.curriculum_id)
  is distinct from (excluded.curriculum_id);
